---
# IOS specific settings
#
device_os: ios
provider: "{{ cli }}"
cli:
  host: "{{ ios_cli_host | default(inventory_hostname) }}"
  username: "{{ ios_cli_user | default('user') }}"
  password: "{{ ios_cli_pass | default('password') }}"
  transport: cli
  authorize: yes
